spring.application.name=order
server.port=8087

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=jdbc:postgresql://localhost:5432/swiftcart
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ReplaceThisWithAStrongRandomSecretKeyOfAtLeast32Chars
jwt.expiration-ms=3600000 


# Actuator base path
management.endpoints.web.base-path=/actuator

# Expose what you need
management.endpoints.web.exposure.include=*

# Optional but useful
management.endpoint.health.show-details=always
management.endpoint.mappings.enabled=true
management.health.circuitbreaker.enabled=true

# --- Circuit Breaker Config ---
resilience4j.circuitbreaker.instances.myBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.myBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.myBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.myBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.myBreaker.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.myBreaker.permitted-number-of-calls-in-half-open-state=3


# Kafka Bootstrap Server

spring.kafka.bootstrap-servers=localhost:9092

# Consumer Configuration

spring.kafka.consumer.group-id=swiftcart-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Producer Configuration

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
